init:
 #-ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
 
image: Visual Studio 2017

skip_commits:
  message: /\[chore\]/

version: 0.0.{build}
configuration: Release
platform: x64
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
- cmd: get-SRT-libraries.bat
build:
  project: Cinegy.Srt.sln
  verbosity: minimal
after_build:
- cmd: >-
    7z a Cinegy.Srt.Recv-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\Cinegy.Srt.Recv\bin\Release\Cinegy.Srt.Recv.exe
        
    appveyor PushArtifact Cinegy.Srt.Recv-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.zip
    
    7z a Cinegy.Srt.StreamAnalyser-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\Cinegy.Srt.StreamAnalyser\bin\Release\Cinegy.Srt.StreamAnalyser.exe
    
    appveyor PushArtifact Cinegy.Srt.StreamAnalyser-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.zip
    
    7z a Cinegy.Srt.Recv-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-PDB.zip %APPVEYOR_BUILD_FOLDER%\Cinegy.Srt.Recv\bin\Release
    
    appveyor PushArtifact Cinegy.Srt.Recv-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-PDB.zip
    
    7z a Cinegy.Srt.StreamAnalyser-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-PDB.zip %APPVEYOR_BUILD_FOLDER%\Cinegy.Srt.StreamAnalyser\bin\Release

    appveyor PushArtifact Cinegy.Srt.StreamAnalyser-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-PDB.zip

on_finish:
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
