init:
 - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
 
image: Visual Studio 2022

skip_commits:
  message: /\[chore\]/

version: 0.0.{build}
configuration: Release
platform: x64
before_build:
- cmd: nuget restore
build:
  project: Cinegy.Srt.sln
  verbosity: minimal
after_build:
- cmd: >-  
    7z a Cinegy.Srt.Recv-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-PDB.zip %APPVEYOR_BUILD_FOLDER%\Cinegy.Srt.Recv\bin
    appveyor PushArtifact Cinegy.Srt.Recv-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-PDB.zip
    
    7z a Cinegy.Srt.StreamAnalyser-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-PDB.zip %APPVEYOR_BUILD_FOLDER%\Cinegy.Srt.StreamAnalyser\bin
    appveyor PushArtifact Cinegy.Srt.StreamAnalyser-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-PDB.zip

on_finish:
 - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
